############################################################
#
# web访问端口号  约定：8088
#
############################################################
server:
  port: 8888
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB

  ############################################################
  #
  # 配置数据源信息
  #
  ############################################################
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource          # 数据源类型：HikariCP
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/foodmall?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2b8
    username: root
    password: root
    hikari:
      connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      minimum-idle: 5                 # 最小连接数
      maximum-pool-size: 20           # 最大连接数
      auto-commit: true               # 自动提交
      idle-timeout: 600000            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP     # 连接池名字
      max-lifetime: 1800000           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      connection-test-query: SELECT 1



  ############################################################
  #
  # mybatis 配置
  #
  ############################################################
  mybatis:
    type-aliases-package: com.pojo          # 所有POJO类所在包路径
    mapper-locations: classpath:mapper/*.xml      # mapper映射文件

    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  ############################################################
  #
  # mybatis mapper 配置
  #
  ############################################################
  # 通用 Mapper 配置
#  mapper:
#    mappers: com.mymapper
#    not-empty: false
#    identity: MYSQL


# mybatis-plus相关配置
#mybatis-plus:
#  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
#  mapper-locations: classpath:mapper/*.xml
#  # 以下配置均有默认值,可以不设置
#  global-config:
#    db-config:
#      #主键类型  auto:"数据库ID自增" 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
#      id-type: auto
#      #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
#      field-strategy: NOT_EMPTY
#      #数据库类型
#      db-type: MYSQL
#  configuration:
#    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
#    map-underscore-to-camel-case: true
#    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
#    call-setters-on-nulls: true
#    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#控制台查看SQL执行状况
#logging:
#  level:
#    com.yurui.rediscache: debug



